backend:
  name: git-gateway
  branch: main # أو أي فرع بتستخدمه
  repo: momo582/Sinbellaween-Sports-Club

media_folder: "assets/photos" # مسار رفع الصور
public_folder: "/assets/photos" # رابط الصور

collections:
  - name: "news" # اسم القسم
    label: "news"
    folder: "content/news" # مكان تخزين المقالات
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
