backend:
  name: github
  repo: momo582/Sinbellaween-Sports-Club # اسم مستودعك
  branch: main # أو master حسب فرع مشروعك

media_folder: "photos/uploads" # مسار رفع الصور
public_folder: "/photos/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
